apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\gabriel.casascorral\generic-crawler\kompose.exe convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\gabriel.casascorral\generic-crawler\kompose.exe convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: config-server
    spec:
      containers:
      - image: config_server:latest
        imagePullPolicy: ""
        name: config-server
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
