version: '2'
services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    build: .
#    ports:
#      - "9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ~/mongodata:/data/db
      - ~/mongodataconfig:/data/configdb
  eureka_server:
    image: eureka_server:latest
    ports:
      - "8761:8761"    
  config_server:
    image: config_server:latest
    ports:
      - "8888:8888"
